project:
  type: book
  output-dir: docs

book:
  title: "Statistics Minus the Math 2.0"
  author: "Nathan Favero"
  date: "2/5/2026"
  chapters:
    - index.qmd
    - part: "Describing Data"
      chapters:
      - getting-started.qmd
      - describing-one-variable.qmd
      - correlation.qmd
      - qual-associations.qmd
    - part: "Estimation"
      chapters:
      - stat-inference.qmd
      - prob-models.qmd
      - sampling-distributions.qmd
      - h-tests.qmd
      - h-tests-applied.qmd
    - part: "Putting Data to Work"
      chapters:
      - causality.qmd
      - measurement.qmd
      - regression.qmd
#      - practical-points.qmd
    - teaching-resources.qmd
    - change-log.qmd

#bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
  pdf:
    documentclass: scrreprt
